

import type { Metadata } from "next";
import "./globals.css";

import { Noto_Sans_Bengali } from 'next/font/google';

const notoSansBengali = Noto_Sans_Bengali({ subsets: ['bengali'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bn">
      <body
        className={notoSansBengali.className}
      >
      <main>
        <div >
        {children}
        </div>
      </main>
      </body>
    </html>
  );
}
